### ISSUE TITLE
scons-4.2.0: package build fails, can't find scons.1 

### ISSUE THREAD

**Issue by sagitter** [SCons/scons#3989] opened 2021-08-01 16:09 UTC
** what looks like the actual problem **

`setup.py install -O1 --skip-build --root /home/sagitter/rpmbuild/BUILDROOT/scons-4.2.0-1.fc34.x86_64 --install-scripts=/usr/bin --install-data=/usr/share`

yields.

```
running install_data
error: can't copy 'scons.1': doesn't exist or not a regular file
```

** Initial report **

Hi all.

**Describe the bug**
Scons manpages are not created in build time (see full [scons-4.2.0-buildlog.txt](https://github.com/SCons/scons/files/6912955/scons-4.2.0-buildlog.txt) attached):

```
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
__xinclude_lxml(["scons_xi.xml"], ["scons.xml"])
__build_lxml(["scons_db.xml"], ["scons_xi.xml"])
__build_lxml(["scons-scons.fo"], ["scons_db.xml"])
/usr/bin/fop -fo scons-scons.fo -pdf scons-scons.pdf
Aug 01, 2021 5:52:32 PM org.apache.fop.apps.FOUserAgent processEvent
SEVERE: Invalid property value encountered in margin-left="": org.apache.fop.fo.expr.PropertyException: file:/home/sagitter/rpmbuild/BUILD/scons-4.2.0/build/doc/man/scons-scons.fo:3:6: No conversion defined ; property:'margin-left' (See position 147:8)
org.apache.fop.fo.expr.PropertyException: file:/home/sagitter/rpmbuild/BUILD/scons-4.2.0/build/doc/man/scons-scons.fo:3:6: No conversion defined ; property:'margin-left'
	at org.apache.fop.fo.properties.PropertyMaker.make(PropertyMaker.java:446)
	at org.apache.fop.fo.PropertyList.convertAttributeToProperty(PropertyList.java:499)
	at org.apache.fop.fo.PropertyList.addAttributesToList(PropertyList.java:386)
	at org.apache.fop.fo.FObj.processNode(FObj.java:129)
	at org.apache.fop.fo.FOTreeBuilder$MainFOHandler.startElement(FOTreeBuilder.java:293)
	at org.apache.fop.fo.FOTreeBuilder.startElement(FOTreeBuilder.java:179)
	at java.xml/com.sun.org.apache.xml.internal.serializer.ToXMLSAXHandler.closeStartTag(ToXMLSAXHandler.java:206)
	at java.xml/com.sun.org.apache.xml.internal.serializer.ToXMLSAXHandler.characters(ToXMLSAXHandler.java:526)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.characters(AbstractSAXParser.java:547)
	at java.xml/com.sun.org.apache.xerces.internal.xinclude.XIncludeHandler.characters(XIncludeHandler.java:1183)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:477)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:888)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:824)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1216)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:635)
	at java.xml/com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transformIdentity(TransformerImpl.java:687)
	at java.xml/com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transform(TransformerImpl.java:774)
	at java.xml/com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transform(TransformerImpl.java:370)
	at org.apache.fop.cli.InputHandler.transformTo(InputHandler.java:293)
	at org.apache.fop.cli.InputHandler.renderTo(InputHandler.java:116)
	at org.apache.fop.cli.Main.startFOP(Main.java:183)
	at org.apache.fop.cli.Main.main(Main.java:213)
```

**Required information**
* Version of SCons: 4.2.0
* Version of Python: 3.9.6
* What Platform are you on? Linux, Fedora 34
* fop 2.5
* openjdk 11.0.12 2021-07-20
* python sphinx-3.4.3

**Comment by mwichmann** [comment] 2021-08-01 16:26
I've always seen those kinds of errors from fop, which is out of our control, but the manpages build anyway.   And in fact, from your logfile:
```
__build_lxml_noresult(["scons-time.1"], ["scons-time_db.xml"])
__build_lxml_noresult(["scons.1"], ["scons_db.xml"])
__build_lxml_noresult(["sconsign.1"], ["sconsign_db.xml"])
scons: done building targets.
Install file: "build/doc/man/scons-man.epub" as "build/doc/EPUB/scons-man.epub"
lynx -dump /home/mats/github/scons/build/doc/man/scons-scons.html > build/doc/TEXT/scons-man.txt
Install file: "build/doc/man/scons-scons.pdf" as "build/doc/PDF/scons-man.pdf"
Install file: "build/doc/man/scons-scons.html" as "build/doc/HTML/scons-man.html"
Install file: "build/doc/man/scons-scons-time.pdf" as "build/doc/PDF/scons-time-man.pdf"
Install file: "build/doc/man/scons-scons-time.html" as "build/doc/HTML/scons-time-man.html"
Install file: "build/doc/man/scons-sconsign.pdf" as "build/doc/PDF/sconsign-man.pdf"
Install file: "build/doc/man/scons-sconsign.html" as "build/doc/HTML/sconsign-man.html"
Install file: "build/doc/user/scons.css" as "build/doc/HTML/scons.css"
```

That looks like a good build.

For my build just now on rel_4.2.0 branch (also using F34) I get valid-looking roff-style manpages in `build/doc/man` (we normally focus on the html versions here so there have been some past errors in making the .1 pages, but it looks okay to me at the moment).

Perhaps a bit more information?

**Comment by sagitter** [comment] 2021-08-01 16:30
> For my build just now on rel_4.2.0 branch (also using F34) I get valid-looking roff-style manpages in build/doc/man (we normally focus on the html versions here so there have been some past errors in making the .1 pages, but it looks okay to me at the moment).

Yes, sorry. I've just seen, manpages are created but [install command](https://github.com/SCons/scons/files/6912992/scons-install_log.txt) does not find them.

**Comment by mwichmann** [comment] 2021-08-01 16:43
Is the specfile maybe looking in the wrong place?  Odd because the location shouldn't have changed recently in the scons build.

**Comment by bdbaddog** [comment] 2021-08-01 17:42
Hmm. weird.
scons.1 ends up in the packages that we build.

Is there anyway to get setup.py to output where it's looking for scons.1 ?

**Comment by bdbaddog** [comment] 2021-08-01 17:45
I updated the title and description.

**Comment by sagitter** [comment] 2021-08-01 17:49
Hi @bdbaddog 

> Hmm. weird.
> scons.1 ends up in the packages that we build.
> 
> Is there anyway to get setup.py to output where it's looking for scons.1 ?

```
#!python3

import fnmatch
from setuptools import setup
from setuptools.command.build_py import build_py as build_py_orig

import codecs
import os.path


def read(rel_path):
    here = os.path.abspath(os.path.dirname(__file__))
    with codecs.open(os.path.join(here, rel_path), 'r') as fp:
        return fp.read()


def get_version(rel_path):
    for line in read(rel_path).splitlines():
        if line.startswith('__version__'):
            delim = '"' if '"' in line else "'"
            return line.split(delim)[1]
    else:
        raise RuntimeError("Unable to find version string.")


exclude = ['*Tests']


class build_py(build_py_orig):

    def find_package_modules(self, package, package_dir):
        """
        Custom module to find package modules.
        It will strip out any modules which match the glob patters in exclude above
        """
        modules = super().find_package_modules(package, package_dir)
        return [(pkg, mod, file, ) for (pkg, mod, file, ) in modules
                if not any(fnmatch.fnmatchcase(mod, pat=pattern)
                for pattern in exclude)]

setup(
    cmdclass={
        'build_py': build_py,
    },
    version=get_version('SCons/__init__.py'),
)
```

**Comment by bdbaddog** [comment] 2021-08-01 18:48
@sagitter  - Not sure why you pasted the setup.py into the response.. is there some flag we can set to get more verbose output on where it's looking for the file? (The .1's are specfied via setup.cfg)

**Comment by sagitter** [comment] 2021-08-01 19:43
> @sagitter - Not sure why you pasted the setup.py into the response.. 

I misunderstood your comment.

> is there some flag we can set to get more verbose output on where it's looking for the file? (The .1's are specfied via setup.cfg)

I tried by adding `-v` to `/usr/bin/python3 setup.py install -O1 --skip-build --root /home/sagitter/rpmbuild/BUILDROOT/scons-4.2.0-1.fc34.x86_64 --install-scripts=/usr/bin --install-data=/usr/share` without success unfortunately.
In build log i attached, i see 

```
Writing SCons-4.2.0/setup.cfg
Creating tar archive
removing 'SCons-4.2.0' (and everything under it)         <--------------------------
Delete(["scons-time.1", "scons.1", "sconsign.1"])          <--------------------------
Copy("build/doc/design/engine.fig", "doc/design/engine.fig")
Copy("build/doc/design/engine.jpg", "doc/design/engine.jpg")
Copy("build/doc/design/engine.svg", "doc/design/engine.svg")
Copy("build/doc/design/titlepage/bricks.jpg", "doc/design/titlepage/bricks.jpg")
Copy("build/doc/design/titlepage/mapnik_final_colors.svg", "doc/design/titlepage/mapnik_final_colors.svg")
Copy("build/doc/design/titlepage/SCons_path.svg", "doc/design/titlepage/SCons_path.svg")
Copy("build/doc/design/titlepage/SConsBuildBricks_path.svg", "doc/design/titlepage/SConsBuildBricks_path.svg")
```
Is it expected?

**Comment by bdbaddog** [comment] 2021-08-01 20:03
hmm.. ran setup.py under strace here's the relevant bit..

`stat("scons.1", 0x7ffc32f23d40)         = -1 ENOENT (No such file or directory)`

so bdist_wheel finds the file and our own packaging of sdist finds the file.
Curious.

I think install builds the package, then unpacks it in /tmp, then tries to install it from there.

Are you trying to build a package for a distro?

**Comment by sagitter** [comment] 2021-08-01 20:22
> Are you trying to build a package for a distro?

Yes, it's for Fedora

**Comment by bdbaddog** [comment] 2021-08-01 20:22
I can't reproduce that output...
Can you join us on our discord server to discuss?
https://discord.gg/pejaFYrD9n

**Comment by bdbaddog** [comment] 2021-08-01 20:32
OH IC. the output from scons building itself.

O.k. I see the issue.
Strange.

Comment out this line (at the bottom of the ) SConstruct in the base directory and then try packaging again.
`env.AddPostAction(tgz_file, Delete(man_pages))`

You'll need to do this first
`rm -rf .sconsign* build`

**Comment by sagitter** [comment] 2021-08-01 21:04
>Comment out this line (at the bottom of the ) SConstruct in the base directory and then try packaging again.
env.AddPostAction(tgz_file, Delete(man_pages))

It's working now.

**Comment by bdbaddog** [comment] 2021-08-01 21:29
If you do a fresh checkout from rel_4.2.0, this should now be fixed there (and on master branch)

**Comment by bdbaddog** [comment] 2021-08-02 05:06
Closing. 
@sagitter - should updates to rel_4.2.0 not prove fixed, please reopen.

**Closed as completed by bdbaddog** 2021-08-02 05:06 UTC
Labels: Release, Version: 4.2.0

**Comment by sagitter** [comment] 2021-08-02 08:23
Thank you very much.

**Comment by bdbaddog** [comment] 2021-08-02 18:22
Glad to help!
We were thinking about creating a packaging maintainer channel on our discord server to support maintainers like you. 
Please let us know if you think that'd be useful.
