### ISSUE TITLE
can scons support build Visual Studio KMDF build?

### ISSUE THREAD

**Issue by liujincheng** [SCons/scons#3820] opened 2020-11-05 12:14 UTC
**Describe the Feature**
We are developing Windows Kernel Mode driver through Visual Studio 2019, and recently plan to switch to Scons. After studied existing document, only how to develop user mode app is covered, and still not sure if it is possible. 
Can someone give advise? 

bellow are more background. 
https://docs.microsoft.com/zh-cn/windows-hardware/drivers/gettingstarted/writing-a-very-small-kmdf--driver
https://github.com/microsoft/Windows-driver-samples/tree/master/general/pcidrv/kmdf/HW

**Comment by bdbaddog** [comment] 2020-11-05 14:23
@liujincheng -please bring such questions to our users mailing list or our discord server or IRC channel

Info on our mailing lists and discord server and IRC: https://scons.org/lists.html

**Comment by bdbaddog** [comment] 2020-11-05 14:25
Also the Microsoft page you linked to is in Chinese. Please link to an english language page

**Comment by bdbaddog** [comment] 2020-11-05 14:26
In general if windows kernel modules can be built with command line tools, then there's no reason SCons can't be used for such.

**Comment by bdbaddog** [comment] 2020-11-06 01:36
Closing as this is not a bug, but a question. Please use mailing list,  IRC, or discord server for such.

**Closed as completed by bdbaddog** 2020-11-06 01:36 UTC
