### ISSUE TITLE
[test__nonzero__] Failed test by using Python-3.10.0a4

### ISSUE THREAD

**Issue by sagitter** [SCons/scons#3860] opened 2021-01-08 20:16 UTC
Hi all.

**Describe the bug**
scons-4.0.1 fails to build with Python 3.10.0a4.

```
+ /usr/bin/python3 runtest.py -P /usr/bin/python3 --passed --quit-on-failure SCons/BuilderTests.py
1/1 (100.00%) /usr/bin/python3 SCons/BuilderTests.py
....F.................................
======================================================================
FAIL: test__nonzero__ (__main__.BuilderTestCase)
Test a builder raising an exception when __nonzero__ is called
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/scons-4.0.1/SCons/BuilderTests.py", line 233, in test__nonzero__
    assert exc_caught, "did not catch expected InternalError exception"
AssertionError: did not catch expected InternalError exception
```

**Required information**
* SCons-4.0.1
* Python-3.10.0a4
* Python distributed by Fedora RPM
* Test performed during the SCons RPM building
* Fedora 34 (devel branch)
* Full build log: [here](https://copr-be.cloud.fedoraproject.org/results/@python/python3.10/fedora-rawhide-x86_64/01865304-scons/builder-live.log.gz)

**Comment by mwichmann** [comment] 2021-01-08 23:31
Odd. Confused Maybe this?  

> bpo-23898: Fix inspect.classify_class_attrs() to support attributes with overloaded `__eq__` and `__bool__`. Patch by Mike Bayer.

That's in the 3.10 changelog, but the issue itself looks like it was merged way long ago so I'm not understanding.

**Comment by mwichmann** [comment] 2021-01-08 23:35
Unrelated to this, just a note - keep an eye out for a 4.1 release, 4.0 had some issues that have caused trouble for distro packagers.

**Comment by sagitter** [comment] 2021-01-09 11:51
Is `SCons-4.1` release near?

**Comment by mwichmann** [comment] 2021-01-09 18:04
at the moment there's not a specific date, but close, yes. (you'll probably find in the version you're working with the manpage sources are empty, was one issue)

**Comment by mwichmann** [comment] 2021-01-11 17:55
There's definitely something interesting going on here, first poke at python-dev mailing list didn't turn up any responses.  This reproducer is not much smaller than the testcase, but definitely shows the change, extracted from any test harness cruft, etc. (edited, simplified the case more)
```
class A:
    def __bool__(self):
        raise AttributeError("Don't do that")

class B:
    pass

a = A()
b = B()
b.a = a

try:
    if b.a:
        pass
except AttributeError:
    print("Got expected TypeError in second test")
else:
    print("No expected TypeError in second test")
```

The funky thing is if you add a "real" statement, not just `pass` (or ellipses `...`) in the test block, then it triggers...
```
    if b.a:
        _dummy = True
```
Wonder if it's some kind of optimization bug...

**Comment by mwichmann** [comment] 2021-01-11 19:29
So that one-liner, though a hack, works around the test problem without really risking introducing any issues.  Besides, `__nonzero__` is a Py2 relic anyway. @bdbaddog, interested in me excising the `__nonzero__` bits as part of a PR?

**Comment by bdbaddog** [comment] 2021-01-11 19:33
Seems like a python 3.10 bug?

**Comment by mwichmann** [comment] 2021-01-11 20:14
I suspect so, I'm following up that angle, and expect it won't do that by the time it's ready to release (smells like someone's "here's a case where we can optimize away the bytecode) - but it's a testcase with an artificial condition, so it doesn't feel like it would hurt to do it slightly differently either.

**Comment by bdbaddog** [comment] 2021-01-11 21:00
@mwichmann - fair enough. I'd say put a comment there why you've changed the code? Mark it with a  TODO: check if still the case with release 4.10 ?

**Comment by mwichmann** [comment] 2021-01-11 22:54
And so this turns into https://bugs.python.org/issue42899

**Closed as completed** 2021-01-12 19:14 UTC
Labels: Python 3.10

**Comment by mwichmann** [comment] 2021-01-19 20:16
> Is `SCons-4.1` release near?

@sagitter: just dropped, in case the news doesn't propagate.
