### ISSUE TITLE
Enable disabling scanners per Builder()/Command() via source_scanner/target_scanner setting

### ISSUE THREAD

**Issue by acmorrow** [SCons/scons#3974] opened 2021-07-13 15:37 UTC
**Describe the Feature**
It is sometimes surprising to users that the `source` and `target` lists of `Command` builders are implicitly scanned by all scanners in the `SCANNERS` variable, and sometimes this behavior is not desirable for various reasons. While this behavior can be suppressed by adding `SCANNERS=[]` to the `Command` invocation, that is something of a big hammer and doesn't feel aligned with the fact that `Command` admits `source_scanner` and `target_scanner` kwargs. But it isn't easy to use those kwargs either, since you can't pass `False`. Instead, you need to construct a no-op Scanner like such: `source_scanner=env.Scanner(lambda a, b, c: [])`, which isn't very obvious. Instead, we could either update the `Command` builder to accept `False` for `source_scanner` and `target_scanner`, or provide a pre-canned no-op Scanner that can be used: `source_scanner=SCons.Scanners.None`. Other approaches are certainly possible.

**Required information**
* Discussed with @bdbaddog on Discord
* Version of SCons: At least 3.1.2+

**Additional context**

**Comment by mwichmann** [comment] 2022-05-27 13:24
Just noticed this is basically asking for the same thing as #3938.

**Comment by bdbaddog** [comment] 2022-05-27 14:54
Yup. I'll  close as a duplicate of #3938

**Closed as completed by bdbaddog** 2022-05-27 14:54 UTC
Labels: scanner
