### ISSUE TITLE
#3848 seems to have changed/broken $_SHLIBSONAME when SHLIBSUFFIX=''

### ISSUE THREAD

**Issue by JonathonReinhart** [SCons/scons#3883] opened 2021-02-06 05:18 UTC
Overview
-------------
As of #3848, if `SHLIBSUFFIX=''` then `$_SHLIBSONAME` seems to behave incorrectly and now just expands to `lib`.

Background:
- OS: Linux (Debian 10)
- Python: 3.7.3
- Running SCons straight out of git
- Original bug: JonathonReinhart/staticx#167

Bad Behavior
------------------

**`SConstruct`**
```python
env = Environment()
env.SharedLibrary(
    target = 'libdummy.so.7',
    source = env.Textfile(
        target = 'dummy.c',
        source = ['void foo(void) { }'],
    ),
    LINKFLAGS = [
        '-Wl,-soname=$_SHLIBSONAME',
    ],
    SHLIBSUFFIX='',
)
```

Before #3848 (at 3e219eba1311807bde43348c86967d96c5379217):
```
$ python3 ~/gitrepos/scons/scripts/scons.py -Q
gcc -o dummy.os -c -fPIC dummy.c
gcc -o libdummy.so.7 -Wl,-soname=libdummy.so.7 -shared dummy.os
```
-  See that SONAME `libdummy.so.7` is correct

After #3848 (at 9103f7fd58d199c9546d288825fc7bbcc605a025)
```
$ python3 ~/gitrepos/scons/scripts/scons.py -Q
gcc -o dummy.os -c -fPIC dummy.c
gcc -o libdummy.so.7 -Wl,-soname=lib -shared   dummy.os $(  $)
```

- See that SONAME `lib` is *incorrect*
- Also see extra space after `-shared` and extra `$( $)`

Normal Behavior
----------------------
Of course if you don't mess with `SHLIBSUFFIX`, it seems to work correctly:

**`SConstruct`**
```python
env = Environment()
env.SharedLibrary(
    target = 'dummy',
    #target = 'libdummy.so',   # same behavior
    source = env.Textfile(
        target = 'dummy.c',
        source = ['void foo(void) { }'],
    ),
    LINKFLAGS = [
        '-Wl,-soname=$_SHLIBSONAME',
    ],
)
```

Before #3848 (at 3e219eba1311807bde43348c86967d96c5379217):
```
$ python3 ~/gitrepos/scons/scripts/scons.py -Q
gcc -o dummy.os -c -Wall -Werror -fPIC dummy.c
gcc -o libdummy.so -Wl,-soname=libdummy.so -nostdlib -shared dummy.os
```

After #3848 (at 9103f7fd58d199c9546d288825fc7bbcc605a025):
```
python3 ~/gitrepos/scons/scripts/scons.py -Q
gcc -o dummy.os -c -Wall -Werror -fPIC dummy.c
gcc -o libdummy.so -Wl,-soname=libdummy.so -nostdlib -shared   dummy.os $(  $)
```

Explanation
----------------
Now this is arguably *not* a bug in SCons, and can be blamed on the weird way I was using it.

Rationale:
- As part of `libnssfix` in [JonathonReinhart/staticx](https://github.com/JonathonReinhart/staticx), I [generate and build](https://github.com/JonathonReinhart/staticx/blob/v0.12.0/libnssfix/SConscript#L6-L14) a "stub" version of `libc.so.6` to bypass symbol versioning.
- I wanted my tool `ShlibStubGen` to simply take the full name of the library to be generated, rather than having to separately set the `SONAME` override variable.
- But if `target` doesn't end in `.so`, it will get `.so` appended, and the result was the file being named `libc.so.6.so` (and have an soname of the same).
- So I set `SHLIBSUFFIX` to an empty string to let me have full control of the filename
- This worked fine until SCons 4.1.0

Workaround
----------------
In writing up this issue, It looks like my best option is to set both `SONAME` and `SHLIBSUFFIX`:

```python
env = Environment()

name = 'libdummy.so.7'

env.SharedLibrary(
    target = name,
    source = env.Textfile(
        target = 'dummy.c',
        source = ['void foo(void) { }'],
    ),
    LINKFLAGS = [
        '-Wl,-soname=$_SHLIBSONAME',
    ],
    SHLIBSUFFIX = '',
    SONAME = name,
)
```

Before:
```
$ python3 ~/gitrepos/scons/scripts/scons.py -Q
gcc -o dummy.os -c -fPIC dummy.c
gcc -o libdummy.so.7 -Wl,-soname=libdummy.so.7 -shared dummy.os
```

After:
```
$ python3 ~/gitrepos/scons/scripts/scons.py -Q
gcc -o dummy.os -c -fPIC dummy.c
gcc -o libdummy.so.7 -Wl,-soname=libdummy.so.7 -shared   dummy.os $(  $)
```

Alternatively, I can just ignore using `SHLIBSONAME` and just set the name myself:
```python
env = Environment()
env.SharedLibrary(
    target = 'libdummy.so.7',
    source = env.Textfile(
        target = 'dummy.c',
        source = ['void foo(void) { }'],
    ),
    LINKFLAGS = [
        '-Wl,-soname=${TARGET.name}',
    ],
    SHLIBSUFFIX = '',
)
```

---
Feel free to close this as "not a real bug", since I think my "workaround" seems pretty sound.

However, I do thing new build output anomalies are worth looking into.

cc @bdbaddog

**Comment by mwichmann** [comment] 2021-02-06 10:55
Looks like just a small oversight... can you see if this works for you? As written it's not resilient to a zero-length suffix.
```
diff --git a/SCons/Tool/linkCommon/SharedLibrary.py b/SCons/Tool/linkCommon/SharedLibrary.py
index e28addc61..8a68ced24 100644
--- a/SCons/Tool/linkCommon/SharedLibrary.py
+++ b/SCons/Tool/linkCommon/SharedLibrary.py
@@ -138,7 +138,7 @@ def _get_shlib_stem(target, source, env, for_signature):
     if target_name.startswith(shlibprefix):
         target_name = target_name[len(shlibprefix) :]
 
-    if target_name.endswith(shlibsuffix):
+    if shlibsuffix and target_name.endswith(shlibsuffix):
         target_name = target_name[: -len(shlibsuffix)]
 
     if verbose and not for_signature:
```

**Comment by mwichmann** [comment] 2021-02-06 18:39
I can certainly reproduce the included testcase... I tried to gen up a simple case for the testsuite, and it didn't seem to trigger the function that has the problem (I turned on local debug there and nothing is printed), maybe @bdbaddog has thoughts on that (possible candidates being `test/Lib/SHLIBSUFFIX.py and test/LINK/SHLINKCOM.py`).

**Comment by bdbaddog** [comment] 2021-03-18 16:40
From current master.

```
 % python ~/devel/scons/git/as_scons/scripts/scons.py -n
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
gcc -o libdummy.so.7 -Wl,-soname=libdummy.so.7 -dynamiclib   dummy.os $(  $)
scons: done building targets.
```

Fixed. Closing.

@JonathonReinhart - please comment/reopen if I'm misunderstanding the issue and it's not actually fixed.

**Closed as completed by bdbaddog** 2021-03-18 16:40 UTC
Labels: bug, version: 4.1.0

**Comment by mwichmann** [comment] 2021-03-18 16:44
The reference (which I forgot to add to the PR for linkage) is #3899

**Comment by JonathonReinhart** [comment] 2021-03-19 02:15
Looks good, guys. Thanks for the fix.

**Comment by bdbaddog** [comment] 2021-03-19 02:53
> Looks good, guys. Thanks for the fix.

No problem.. The bug was in some new code I wrote.. but that won't happen again as we always add a test to verify we fix issues.. :)
