### ISSUE TITLE
Force SCons to use 32-bit MSVC compiler on 64-bit Windows

### ISSUE THREAD

**Issue by nneesshh** [SCons/scons#3187] opened 2018-08-30 07:48 UTC
See https://stackoverflow.com/questions/24810474/force-scons-to-use-32-bit-msvc-compiler-on-64-bit-windows

I encounted the same bug: I want scons to use x86 version "cl.exe", but it always use x64 version "cl.exe".
When I modified the "C:\Python27\scons-3.0.1\SCons\Environment.py" line 950 

form "self._dict['TARGET_ARCH']    = self._dict.get('TARGET_ARCH',None)" to "self._dict['TARGET_ARCH']    = self._dict.get('TARGET_ARCH','x86')"

It use x86 version "cl.exe" now.

**Comment by bdbaddog** [comment] 2018-08-30 15:41
This is not a bug.
It's by design.
And you're using TARGET_ARCH incorrectly.

You should set it in each Environment() you want to force a specific (non-native) target for MSVC compiles.

This is the correct answer to that stackoverflow question:
https://stackoverflow.com/a/26592583/82681


Closing.

**Closed as completed by bdbaddog** 2018-08-30 15:41 UTC
